# NUMPY

In [1]:
import numpy as np

# 1 D array

In [2]:
x = np.array([5,10,16,20,25,30,35,40])

# Attributes of arrays

## dype

## ndim

## size

## shape 

In [3]:
x.dtype

dtype('int32')

In [4]:
x.shape

(8,)

In [5]:
x.ndim

1

In [6]:
x.size

8

In [7]:
x[0]

5

In [8]:
x[3]

20

# Multi Dimensional array

In [9]:
x_2d = np.array([[23,34,43], [45,55,65]])

In [10]:
x_2d

array([[23, 34, 43],
       [45, 55, 65]])

In [11]:
x_2d.dtype

dtype('int32')

In [12]:
x_2d.shape

(2, 3)

In [13]:
x_2d.ndim

2

In [14]:
x_2d.size

6

In [15]:
x_2d[0]

array([23, 34, 43])

# Another type of multi dimensional arrays

In [16]:
another_type_array = np.array([[[1,2,3,4]]])

In [17]:
another_type_array

array([[[1, 2, 3, 4]]])

In [18]:
another_type_array.shape

(1, 1, 4)

In [19]:
another_type_array.ndim

3

# first element in first array

In [20]:
x_2d[0][0]

23

# second element in second array

In [21]:
x_2d[1][1]

55

# lets change its data type into floAt

In [22]:
a_2d = np.array([[10,20,30] , [32,43,45,]], dtype = float)

In [23]:
a_2d

array([[10., 20., 30.],
       [32., 43., 45.]])

# Lets create a bigger array

In [25]:
a_bigger = np.array([
[
[10,20,30,40],[6,3,6,1],[1,1,1,2]
] ,
[
[9,9,5,5], [2,5,3,6], [0,0,3,2]
] ,
[
[12,33,22,1], [22,1,22,32], [0,2,3,1]    
] ,   
    
], dtype = float)

In [26]:
a_bigger.shape

(3, 3, 4)

In [27]:
a_bigger.ndim

3

In [28]:
a_bigger.size

36

In [29]:
a_bigger[2][2][3]

1.0

In [30]:
a_bigger[2][2]

array([0., 2., 3., 1.])

# Filling Arrays

### np.full

### By using the full functions for example, we fill an array of a certain shape with the same number. in this case we create a 3*5*4 matrix, which is filled with sevens

In [32]:
a_full = np.full((3,4,5,),7)

In [33]:
a_full

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [34]:
a_full = np.full((5,4,3),7)

In [42]:
a_full

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [43]:
a_full.ndim

3

# ZEROS AND ONES

## for the cases that we want arrays full of zeros or ones, we even have specific function. 

In [45]:
a_zeros = np.zeros((3,3))
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
b_ones = np.ones((2,3,4,))
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
b_ones.ndim

3

# EMPTY AND RANDOM

### other options would be to create an empty array or one that is filled with randome numbers . for this, we use the respective functions once again.

In [51]:
e = np.empty((4,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])